// LOOK FOR DB NORMALIZATION AND DENORMALIZATION IN MONGODB.
// EMBED THE DEBT SCHEMA INTO THE DEBT HISTORY! THIS MAKES FOR FASTER QUERIES
// WE CAN FIND A DEBT HISTORY AND ALL ITS ASSOCIATED DEBTS  WITH A SINGLE QUERY
